services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: gamenight
      POSTGRES_PASSWORD: gamenight
      POSTGRES_DB: gamenight
    ports:
      - "5432:5432"
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
